# Generated by Django 3.2 on 2021-05-04 18:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='lectures_num',
            field=models.PositiveIntegerField(validators=[api.models.is_positive], verbose_name='lectures_num'),
        ),
    ]
